export default {
  school: {
    name: "Madinatunnor Madrasha",
    tagline: "[MADRASHA TAGLINE]",
    established: "Established [YEAR]",
    eiin: "EIIN: [NUMBER]",
  },
  nav: {
    home: "Home",
    features: "Features",
    about: "About Us",
    academics: "Academics",
    admission: "Admission",
    gallery: "Gallery",
    contact: "Contact",
    notice: "Notice Board",
  },
  header: {
    signIn: "Sign In",
    toggleMenu: "Toggle menu",
  },
  hero: {
    eyebrow: "Madrasha Management Platform",
    title: "Run Your Madrasha. Not Your Spreadsheets.",
    subtitle: "Attendance, exams, fees, staff, admissions, and parent communication in one connected platform built for madrashas that are done stitching tools together.",
    featuresCta: "Explore Features",
    admissionCta: "Apply for Admission",
    learnMore: "Learn More",
    slide1Title: "Quality Education for All",
    slide1Sub: "State-of-the-art facilities, dedicated faculty, and a vibrant learning environment.",
    slide2Title: "Annual Sports Day 2025",
    slide2Sub: "Celebrating athletic spirit and teamwork across all grade levels.",
    slide3Title: "Science Fair Winners",
    slide3Sub: "Our students shine at the National Science Olympiad 2024.",
  },
  about: {
    title: "About Our Institution",
    subtitle: "Academic excellence, Islamic values, and holistic development.",
    vision: "Vision",
    visionText: "To be a leading madrasha that empowers every learner with deen, knowledge, values, and the skills to thrive in a dynamic world.",
    mission: "Mission",
    missionText: "We foster a safe, disciplined, and stimulating environment where students develop Quranic grounding, intellectual curiosity, moral integrity, and a lifelong love of learning.",
    chairmanTitle: "Chairman's Message",
    chairmanName: "Alhaj Mahmudul Hasan", // placeholder — replace with the real chairman's name
    chairmanInitial: "MH",
    chairmanMessage: "Education is the most powerful tool we can use to change the world. At Madinatunnor Madrasha, we are committed to delivering excellence in both deen and academics, and raising compassionate, principled citizens.",
    principalTitle: "Muhtamim's Message",
    principalName: "Maulana Serajul Islam", // placeholder — replace with the real principal/muhtamim's name
    principalInitial: "SI",
    principalMessage: "Our dedicated team of educators works tirelessly to provide a nurturing environment where every child can discover their potential and achieve their dreams.",
    historyEyebrow: "Institution History",
    historyTitle: "Built on service, discipline, and academic care",
    historyItems: [
      {
        year: "[YEAR]",
        title: "Foundation",
        text: "Madinatunnor Madrasha began with a small group of learners and a commitment to disciplined, caring education rooted in Islamic values.",
      },
      {
        year: "2008",
        title: "Academic Expansion",
        text: "The institution expanded its secondary programs, laboratories, library, and co-curricular activities.",
      },
      {
        year: "2018",
        title: "Digital Campus",
        text: "Classrooms, administration, attendance, results, and guardian communication moved into a modern digital workflow.",
      },
      {
        year: "Today",
        title: "Future-ready Learning",
        text: "The madrasha continues to combine strong academics with values, leadership, and practical skills.",
      },
    ],
    founderEyebrow: "Founder Profile",
    founderName: "Late M. A. Rahman", // placeholder — replace with the real founder's name
    founderText: "The founder envisioned a madrasha where children from every background could receive dependable teaching, moral guidance, and access to modern learning resources. His founding principles continue to guide classroom culture, student care, and community service.",
    founderMotto: "Founder motto: knowledge with character, service with humility.",
    facultyEyebrow: "Faculty & Staff",
    facultyTitle: "Meet Our Faculty",
    facultySubtitle: "Qualified teachers lead academic programs, classroom mentoring, discipline, and student support across every section.",
    facultyFallbackDesignation: "Faculty Member",
    facultyFallbackDepartment: "General",
    facultyFallbackQualification: "Experienced educator",
    departmentLabel: "Department:",
    qualificationLabel: "Qualification:",
    faculty: [
      {
        userId: "public-teacher-1",
        name: "Mawlana Nurul Amin",
        designation: "Head Teacher",
        department: "Islamic Studies",
        qualification: "Kamil, Ifta",
        photoUrl: "/images/sites/madina-madrasha/faculty/1-head-teacher.jpg",
      },
      {
        userId: "public-teacher-2",
        name: "Sumaiya Akhter",
        designation: "Senior Teacher",
        department: "Mathematics",
        qualification: "M.Sc, B.Ed",
        photoUrl: "/images/sites/madina-madrasha/faculty/2-senior-teacher.jpg",
      },
      {
        userId: "public-teacher-3",
        name: "Ashraful Alam",
        designation: "Assistant Teacher",
        department: "Languages",
        qualification: "M.A, B.Ed",
        photoUrl: "/images/sites/madina-madrasha/faculty/3-assistant-teacher.jpg",
      },
      {
        userId: "public-teacher-4",
        name: "Tania Ferdous",
        designation: "ICT Teacher",
        department: "ICT",
        qualification: "B.Sc in CSE",
        photoUrl: "/images/sites/madina-madrasha/faculty/4-ict-teacher.jpg",
      },
    ],
    orgEyebrow: "Organizational Structure",
    orgTitle: "Leadership with clarity, accountability, and daily direction",
    orgText: "Each layer of leadership has a defined role, creating a reliable chain from governance and academic planning to student care, discipline, and classroom guidance.",
    orgHighlights: [
      { label: "Governance", value: "Strategic oversight" },
      { label: "Academics", value: "Teaching direction" },
      { label: "Students", value: "Daily support" },
    ],
    leadershipEyebrow: "Leadership Chain",
    leadershipTitle: "Who guides the institution day to day",
    leadershipBadge: "Accountable and role-based",
    levelLabel: "Level {number}",
    leadership: [
      { role: "Governing Body", name: "Strategic direction and institutional policy" },
      { role: "Chairman", name: "Alhaj Mahmudul Hasan" },
      { role: "Principal", name: "Maulana Serajul Islam" },
      { role: "Academic Coordinators", name: "Section planning, routines, exams, and teacher support" },
      { role: "Class Teachers", name: "Student care, attendance, guardians, and daily classroom guidance" },
    ],
  },
  stats: {
    students: "Students",
    teachers: "Teachers",
    departments: "Departments",
    yearsOfExcellence: "Years of Excellence",
  },
  notice: {
    title: "Notice Board",
    subtitle: "Stay updated with the latest announcements and news.",
    newsTitle: "Latest News",
    noNotices: "No notices at this time. Please check back later.",
    readMore: "Read More",
    viewAll: "View All Notices",
    emptyNotices: "No notices yet.",
    emptyNews: "No news yet.",
    sample1: "Annual Examination Schedule - Class VI to X (December 2025)",
    sample2: "Admission Open for Session 2026 - Apply Before 31 January",
    sample3: "Parent-Teacher Meeting: Saturday, 20 December 2025 at 10:00 AM",
    sample4: "Madrasha closed on 16 December 2025 (Victory Day)",
    news1: "Madinatunnor students win Gold at the District Science Fair 2025",
    news2: "New Computer Lab inaugurated with 40 modern workstations",
    news3: "Results: 98% pass rate in Dakhil 2025 - highest in the district",
  },
  features: {
    eyebrow: "Platform Features",
    title: "One Platform to Run Your Entire Madrasha",
    subtitle: "Enrollment, attendance, exams, fees, staff, and parent communication built in, connected, and working together from day one.",
    attendanceTitle: "Attendance & Exams",
    attendanceDesc: "Mark attendance in seconds, keep a clean audit trail of corrections, and manage exam schedules, results, and grading policies without spreadsheets.",
    attendanceBullet1: "Daily and period-wise attendance with bulk import",
    attendanceBullet2: "Correction requests with an approval workflow, not silent edits",
    attendanceBullet3: "Exam schedules, results entry, and configurable grading policies",
    feesTitle: "Fees & Accounting",
    feesDesc: "Set up fee categories once, assign them per student, and let the system generate invoices, track payments, and show you exactly what is due.",
    feesBullet1: "Tuition, exam, transport - any fee category, with discounts and waivers",
    feesBullet2: "Automatic invoice generation and receipt records for every payment",
    feesBullet3: "Real-time dues and collection totals, no manual reconciliation",
    communicationTitle: "Communication & Portals",
    communicationDesc: "Admins, teachers, and guardians message each other directly inside the platform with dedicated portals so every family sees only their own child.",
    communicationBullet1: "Direct messaging between admin, teacher, and guardian accounts",
    communicationBullet2: "Guardian portal: results, attendance, and fee status in real time",
    communicationBullet3: "Notice board and news feed, filtered by audience",
    reportsTitle: "Admin Reports & Analytics",
    reportsDesc: "A dashboard built for the questions a madrasha admin actually asks, not a spreadsheet export you have to interpret yourself.",
    reportsBullet1: "Class-wise and gender-wise enrollment at a glance",
    reportsBullet2: "Daily and monthly attendance percentage, with an absentee list",
    reportsBullet3: "Exam pass rates and fee collection, broken down by class",
    placeholderLabel: "Screenshot placeholder - {title}",
    gridTitle: "And everything else a running madrasha needs",
    gridSubtitle: "The parts that do not need a screenshot to matter.",
    gridStudentsTitle: "Student & Teacher Records",
    gridStudentsDesc: "Full profiles, class assignment, and roll numbers - the single source of truth for who is enrolled where.",
    gridAdmissionsTitle: "Online Admissions",
    gridAdmissionsDesc: "A public application form with document upload, verification status, and a reference code parents can track.",
    gridHrTitle: "HR & Staff Management",
    gridHrDesc: "Non-teaching staff records, attendance, leave requests, and payroll, not just teachers.",
    gridMultiSchoolTitle: "Multi-School Ready",
    gridMultiSchoolDesc: "Every institution's data is isolated on one shared platform - one login system, many institutions.",
    gridSecurityTitle: "Security & Access Control",
    gridSecurityDesc: "Role-based permissions, audit logs on sensitive actions, and account lockout protection built in.",
    gridBilingualTitle: "Bilingual by Default",
    gridBilingualDesc: "Every portal and public page works in English and Bangla, switchable in one click.",
    ctaTitle: "See it running on your own madrasha's data",
    ctaSubtitle: "Get in touch and we will set up a walkthrough of the exact modules your madrasha needs.",
    ctaButton: "Talk to Us",
  },
  preview: {
    eyebrow: "Inside the Platform",
    title: "See the whole madrasha. Act on what matters.",
    subtitle: "A decision-ready workspace that brings academics, attendance, admissions, finance, and communication into one calm, connected view.",
    tabLabel: "Choose a dashboard preview",
    tabs: {
      operations: "Operations",
      academics: "Academics",
      finance: "Finance",
    },
    browserUrl: "app.madinatunnormadrasha.edu.bd/dashboard",
    productName: "Madina OS",
    panelName: "Madrasha command centre",
    workspace: "Madinatunnor Madrasha",
    search: "Search the platform",
    liveStatus: "Live data",
    chartLegend: "This week",
    activityTitle: "Recent activity",
    viewAll: "View all",
    recently: "Updated moments ago",
    adminInitials: "SI",
    adminName: "Serajul Islam",
    adminRole: "Principal",
    sidebar: {
      overview: "Overview",
      academics: "Academics",
      people: "Students & Staff",
      finance: "Finance",
      reports: "Reports",
    },
    days: {
      sat: "Sat",
      sun: "Sun",
      mon: "Mon",
      tue: "Tue",
      wed: "Wed",
      thu: "Thu",
      fri: "Fri",
    },
    proof1: "One reliable source of truth across departments",
    proof2: "Role-based access for every madrasha team",
    proof3: "English and Bangla from the same live data",
    views: {
      operations: {
        title: "Operations Overview",
        heading: "Good morning, Serajul",
        subheading: "Here is what needs attention today.",
        chartTitle: "Weekly attendance",
        chartSubtitle: "Whole-madrasha attendance by day",
        stats: {
          students: { value: "2,418", label: "Active students" },
          teachers: { value: "91", label: "Teachers & staff" },
          attendance: { value: "94.8%", label: "Present today" },
          admissions: { value: "12", label: "Applications pending" },
        },
        activity1: "Class VIII attendance completed",
        activity2: "Three admission files verified",
        activity3: "Guardian notice delivered",
      },
      academics: {
        title: "Academic Performance",
        heading: "Learning progress at a glance",
        subheading: "Track teaching, assessment, and outcomes together.",
        chartTitle: "Syllabus completion",
        chartSubtitle: "Weekly progress across active classes",
        stats: {
          classes: { value: "32", label: "Active classes" },
          exams: { value: "8", label: "Assessments scheduled" },
          passRate: { value: "98.2%", label: "Current pass rate" },
          lessons: { value: "21", label: "Lessons this week" },
        },
        activity1: "Half-yearly routine published",
        activity2: "Class X results approved",
        activity3: "Science syllabus updated",
      },
      finance: {
        title: "Fees & Accounting",
        heading: "Collections without reconciliation guesswork",
        subheading: "Every invoice, payment, due, and receipt stays connected.",
        chartTitle: "Collection trend",
        chartSubtitle: "Daily fee collection for this week",
        stats: {
          collected: { value: "৳8.42L", label: "Collected this month" },
          outstanding: { value: "৳1.18L", label: "Outstanding dues" },
          collectionRate: { value: "86%", label: "Collection rate" },
          receipts: { value: "124", label: "Receipts issued" },
        },
        activity1: "Monthly invoices generated",
        activity2: "Transport payment reconciled",
        activity3: "Due reminder sent to guardians",
      },
    },
  },
  testimonials: {
    eyebrow: "Madrasha Community",
    title: "Small operational changes. A noticeably better madrasha day.",
    subtitle: "The platform is designed around the moments that create friction for leadership, teachers, and families, then turns them into one dependable flow.",
    note: "Perspectives from the Madinatunnor Madrasha demo community.",
    principal: {
      quote: "Before the first bell, I can see attendance, pending admissions, fee movement, and the items that need a decision. The day starts with clarity.",
      initials: "SI",
      name: "Maulana Serajul Islam",
      role: "Principal, Madinatunnor Madrasha",
    },
    teacher: {
      quote: "Attendance, assessment entry, and guardian updates now sit in the same flow, so administration no longer follows me back home.",
      initials: "NA",
      name: "Mawlana Nurul Amin",
      role: "Head Teacher, Islamic Studies",
    },
    guardian: {
      quote: "I do not have to call the office to know what is happening. Results, attendance, fees, and notices are already there when I need them.",
      initials: "SR",
      name: "Sadia Rahman",
      role: "Guardian",
    },
  },
  faq: {
    eyebrow: "Questions, Answered",
    title: "What madrashas ask before they move forward",
    subtitle: "Straight answers about setup, data, training, access, and how the platform fits an existing institution.",
    askMore: "Have another question? Talk to us",
    item1: {
      question: "How long does implementation usually take?",
      answer: "A focused rollout can begin with core setup, users, classes, and the most important modules first. The complete timeline depends on institution size, data quality, and the modules selected; we confirm a practical phased plan before any migration begins.",
    },
    item2: {
      question: "Can our existing student and fee data be imported?",
      answer: "Yes. Existing spreadsheets can be mapped, checked, and imported into the relevant records. We validate structure and duplicates first so old data problems are not silently carried into the new system.",
    },
    item3: {
      question: "Does the platform work in both Bangla and English?",
      answer: "Yes. The public website and supported portal experiences can switch between Bangla and English while using the same underlying madrasha data, so language choice never creates duplicate records.",
    },
    item4: {
      question: "How is access controlled for different users?",
      answer: "Role-based permissions limit each user to the information and actions relevant to them. Sensitive operations can also be tracked through approval flows and audit history.",
    },
    item5: {
      question: "Will teachers and office staff receive training?",
      answer: "Yes. Rollout can include role-specific onboarding for leadership, teachers, accounts, and office teams, supported by guided workflows and a staged adoption plan.",
    },
    item6: {
      question: "Does it fit madrashas as well as schools and colleges?",
      answer: "Yes. The platform is structured around configurable classes, sections, academic cycles, fees, staff, and role-based portals — including Dakhil/Alim-style class structures and Islamic Studies subjects for madrashas. The exact setup can be adapted to the institution's level, terminology, and operating process.",
    },
  },
  demo: {
    eyebrow: "A Guided Walkthrough",
    title: "Bring your current process. Leave with a clearer one.",
    subtitle: "Show us how your institution works today. We will walk through the relevant modules and map a realistic first phase around your priorities.",
    primaryCta: "Book a free walkthrough",
    secondaryCta: "Explore platform features",
    proof1: "30-minute focused session",
    proof2: "No commitment",
    proof3: "English or Bangla",
    processLabel: "What happens next",
    step1Number: "01",
    step1Title: "Tell us how you work",
    step1Text: "Share the current tools, bottlenecks, and priorities.",
    step2Number: "02",
    step2Title: "See the relevant modules",
    step2Text: "Walk through workflows that match each madrasha role.",
    step3Number: "03",
    step3Title: "Get a practical rollout path",
    step3Text: "Leave with a clear first phase and next decisions.",
  },
  campus: {
    eyebrow: "Campus & Facilities",
    title: "Life on Campus",
    subtitle: "A glimpse of the classrooms, labs, and learning spaces students spend their day in.",
    teacherClass: "Engaged Classrooms",
    activeLearning: "Active Learning",
    studyTime: "Focused Study Time",
    modernClassroom: "Modern Classrooms",
    scienceLab: "Science Laboratory",
    experiments: "Hands-on Experiments",
    library: "Well-Stocked Library",
    digitalLearning: "Digital Learning",
  },
  whyChooseUs: {
    title: "Why Choose Us",
    subtitle: "What makes Madinatunnor Madrasha the right choice for your child.",
    facultyTitle: "Experienced Faculty",
    facultyDesc: "A caring, qualified teaching staff dedicated to every student's growth.",
    curriculumTitle: "Modern Curriculum",
    curriculumDesc: "A balanced blend of Islamic studies, science labs, general academics, and sports.",
    campusTitle: "Safe Campus",
    campusDesc: "A secure, disciplined environment where students can focus and thrive.",
    portalTitle: "Digital Parent Portal",
    portalDesc: "Parents and students track results, attendance, and notices online, anytime.",
  },
  academics: {
    title: "Academic Programs",
    subtitle: "Comprehensive curricula from Pre-Primary to Higher Secondary.",
    primaryTitle: "Primary Section",
    primaryDesc: "Class I - V · Play-based and foundational learning.",
    juniorTitle: "Junior Secondary",
    juniorDesc: "Class VI - VIII · Core sciences, arts, and languages.",
    secondaryTitle: "Secondary (Dakhil)",
    secondaryDesc: "Class IX - X · Science, Humanities & Islamic Studies.",
    higherTitle: "Higher Secondary (Alim)",
    higherDesc: "Class XI - XII · Science, Humanities & Islamic Studies.",
    examSchedule: "Exam Schedule",
    syllabus: "Download Syllabus",
    viewMore: "View Full Curriculum",
    modalEyebrow: "Exam Planning",
    modalTitle: "Academic exam timeline for the current session",
    modalSubtitle: "A clean overview of the major assessment checkpoints, designed to help students and families prepare with confidence.",
    closeModal: "Close exam schedule",
    phaseLabel: "Phase {number}",
    windowEyebrow: "Assessment Window",
    windowTitle: "January to December 2026",
    windowText: "Class tests, term evaluations, revision cycles, and the final annual examination follow a structured academic calendar.",
    noteEyebrow: "Important Notes",
    note1: "Detailed subject-wise routines are shared before each examination window.",
    note2: "Admit cards, seating plans, and classroom instructions are published through the madrasha notice flow.",
    note3: "Guardians are advised to track attendance and preparation milestones throughout the session.",
    schedule1: {
      title: "First Term Assessment",
      date: "March 2026",
      desc: "Initial progress review covering the early syllabus blocks, class participation, and foundational subject readiness.",
    },
    schedule2: {
      title: "Half-Yearly Examination",
      date: "June 2026",
      desc: "Mid-session evaluation across core subjects, practical activities, and written performance benchmarks.",
    },
    schedule3: {
      title: "Second Term Review",
      date: "September 2026",
      desc: "A focused checkpoint used for revision planning, academic support, and final exam preparation strategy.",
    },
    schedule4: {
      title: "Annual Examination",
      date: "November to December 2026",
      desc: "Comprehensive end-of-year assessment followed by result publication, promotion review, and guardian communication.",
    },
    curriculumEyebrow: "Curriculum Overview",
    curriculumTitle: "A complete view of the learning journey",
    curriculumSubtitle: "Each academic stage is designed with age-appropriate depth, subject balance, and a steady progression toward confident, exam-ready learning.",
    closeCurriculumModal: "Close curriculum overview",
    curriculumSupportEyebrow: "Learning Support",
    curriculumSupportTitle: "Built around steady academic growth",
    curriculumSupportText: "Classroom teaching is supported by assessments, revision structure, practical work, co-curricular exposure, and guardian communication throughout the year.",
    curriculumNoteEyebrow: "What families can expect",
    curriculumNote1: "Regular classwork, homework, and term reviews keep learning measurable.",
    curriculumNote2: "Teachers adjust support based on student progress and subject readiness.",
    curriculumNote3: "Curriculum planning is aligned with both academic outcomes and character development.",
    curriculum1: {
      range: "Class I to V",
      title: "Foundational Primary Learning",
      desc: "Early academic confidence is built through language, numeracy, observation, and disciplined classroom habits.",
      point1: "Strong grounding in Quran recitation, Bangla, English, Mathematics, and General Science.",
      point2: "Reading, handwriting, speaking confidence, and value-based Islamic development.",
    },
    curriculum2: {
      range: "Class VI to VIII",
      title: "Junior Secondary Development",
      desc: "Students deepen subject understanding while building responsibility, analytical thinking, and communication skills.",
      point1: "Core sciences, arts, languages, ICT, and guided project work.",
      point2: "Routine-based study discipline with increasing academic independence.",
    },
    curriculum3: {
      range: "Class IX to X",
      title: "Secondary Board Preparation",
      desc: "Academic plans become more focused, with structured revision and examination support for board readiness.",
      point1: "Stream-sensitive subject planning with model tests and progress tracking.",
      point2: "Balanced preparation across theory, practical work, and written performance.",
    },
    curriculum4: {
      range: "Class XI to XII",
      title: "Higher Secondary Progression",
      desc: "Advanced subject coverage is paired with disciplined preparation, maturity, and future pathway awareness.",
      point1: "Higher-order problem solving, chapter completion targets, and test cycles.",
      point2: "Preparation for public exams, university direction, and independent study habits.",
    },
  },
  admission: {
    title: "Admission 2026",
    announcement: "Admissions are now open for the academic session 2026. Limited seats are available across all classes. Apply early to secure your place.",
    applyNow: "Apply Now",
    downloadForm: "Download Form",
    checkStatus: "Check Status",
    importantDates: "Important Dates",
    date1: "Application Start: 1 January 2026",
    date2: "Last Date to Apply: 31 January 2026",
    date3: "Admission Test: 10 February 2026",
    date4: "Results Published: 15 February 2026",
    eligibility: "Eligibility",
    eligibilityText: "Open to all students who have passed the preceding class from any recognised board or institution.",
    documents: "Required Documents",
    doc1: "Birth certificate (photocopy)",
    doc2: "Previous school's Transfer Certificate",
    doc3: "Last exam mark sheet",
    doc4: "Two passport-size photographs",
    doc5: "Guardian's NID photocopy",
    page: {
      back: "Back to website",
      eyebrow: "Admissions",
      title: "Online Admission",
      subtitle: "Apply for admission in a few minutes, or check the status of an application you've already submitted.",
      newApplication: "New Application",
      statusTab: "Check Status",
      applicantDetails: "Applicant Details",
      applicantSubtitle: "Tell us about the student applying",
      applicantName: "Applicant Full Name *",
      applicantNamePlaceholder: "e.g. Rahim Uddin",
      dateOfBirth: "Date of Birth",
      gender: "Gender",
      selectOption: "Select...",
      genderMale: "Male",
      genderFemale: "Female",
      genderOther: "Other",
      applyingForClass: "Applying For Class *",
      selectClass: "Select a class...",
      previousSchool: "Previous School",
      optional: "Optional",
      applicantPhoto: "Applicant Photo",
      readImageError: "Could not read image file.",
      readDocumentError: "Could not read document file.",
      processDocumentError: "Could not process document.",
      processPhotoError: "Could not process photo.",
      documentTooLarge: "Each document must be 5MB or smaller.",
      supportingDocuments: "Supporting Documents",
      supportingDocumentsSubtitle: "PDF or image, up to 5MB each - all optional at this stage",
      uploadPrompt: "Click to upload",
      birthCertificate: "Birth Certificate",
      previousSchoolCertificate: "Previous School Certificate",
      transferCertificate: "Transfer Certificate",
      guardianIdentity: "Guardian NID/Passport",
      guardianInfo: "Guardian Information",
      guardianSubtitle: "We'll use this to contact you about the application",
      guardianName: "Guardian Name *",
      guardianNamePlaceholder: "e.g. Karim Uddin",
      guardianPhone: "Guardian Phone *",
      guardianPhonePlaceholder: "+880 1700-000000",
      guardianEmail: "Guardian Email",
      submitApplication: "Submit Application",
      submitting: "Submitting...",
      submitError: "Something went wrong. Please try again.",
      submittedTitle: "Application Submitted!",
      submittedText: "Save this reference code - you'll need it to check your application status.",
      copied: "Copied",
      copy: "Copy",
      referenceCode: "Reference Code *",
      referencePlaceholder: "ADM-XXXXXX",
      checking: "Checking...",
      noMatch: "No matching application found.",
      statusFor: "Applying for {className}",
      statusLabel: "Status",
      testScheduled: "Test scheduled: {date}",
      statusSubmitted: "Submitted",
      statusUnderReview: "Under Review",
      statusTestScheduled: "Test Scheduled",
      statusAccepted: "Accepted",
      statusRejected: "Rejected"
    }
  },
  gallery: {
    title: "Photo Gallery",
    subtitle: "Glimpses of life at Madinatunnor Madrasha.",
    viewAll: "View Full Gallery",
    empty: "Gallery photos coming soon.",
    videoTitle: "Gallery video",
  },
  contact: {
    title: "Get in Touch",
    subtitle: "We would love to hear from you.",
    address: "Dhaka, Bangladesh", // on file for this tenant — confirm/replace with the full street address
    phone: "01678560660",
    email: "[PUBLIC CONTACT EMAIL — admin@madina.com on file is the login/admin email, may not be the public one]",
    mapTitle: "Our Location",
    form: {
      title: "Send Us a Message",
      name: "Your Name",
      phone: "Phone Number",
      message: "Your Message",
      submit: "Send Message",
      submitting: "Sending...",
      success: "Thank you. Your message has been sent. We will get back to you soon.",
      error: "Something went wrong. Please try again.",
      namePlaceholder: "e.g. Md. Rafiqul Islam",
      phonePlaceholder: "01XXXXXXXXX",
      messagePlaceholder: "How can we help you?",
    },
  },
  footer: {
    description: "Committed to academic excellence, Islamic values, and the holistic development of every student.",
    quickLinks: "Quick Links",
    schoolAccess: "Madrasha Access",
    schoolAccessLinks: {
      studentPortal: "Student Portal",
      admissionProcess: "Admission Process",
      academicStructure: "Academic Structure",
      campusGallery: "Campus Gallery",
    },
    contact: "Contact",
    followUs: "Follow Us",
    bottomNote: "Designed for modern madrasha communication, operations, and family trust.",
    copyright: "© {year} Madinatunnor Madrasha. All rights reserved.",
  },
};
