import { useEffect, useState } from 'react';
import { BriefcaseBusiness, CalendarCheck, FileText, Loader2, Plus, Save, Star, Trash2, WalletCards } from 'lucide-react';
import { addPerformanceNote, addStaffDocument, deleteStaff, getHrOverview, markStaffAttendance, requestStaffLeave, reviewStaffLeave, savePayroll, saveStaff } from '../../../services/api/hrApi.js';

const TABS = ['Staff', 'Attendance', 'Leave', 'Payroll', 'Documents', 'Performance'];
const today = () => new Date().toISOString().slice(0,10);
const month = () => new Date().toISOString().slice(0,7);
const money = (n) => `BDT ${Number(n||0).toLocaleString('en-BD',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function Field({label,children}){return <label className="block"><span className="label-sm">{label}</span>{children}</label>}
function Input(p){return <input {...p} className={`input ${p.className||''}`} />}
function Select(p){return <select {...p} className={`input ${p.className||''}`} />}
function Empty({children}){return <div className="rounded-2xl border-2 border-dashed border-slate-200 py-12 text-center text-sm text-slate-400">{children}</div>}
function Stat({icon:Icon,label,value,color}){return <div className="card flex items-center gap-4"><span className={`flex h-11 w-11 items-center justify-center rounded-2xl ${color}`}><Icon className="h-5 w-5" /></span><div><p className="text-xl font-black text-slate-800">{value}</p><p className="text-xs text-slate-400">{label}</p></div></div>}

export default function HrPage(){
  const [active,setActive]=useState('Staff'); const [data,setData]=useState(null); const [loading,setLoading]=useState(true);
  const [staffForm,setStaffForm]=useState({name:'',staffType:'non_teaching',employeeId:'',designation:'',department:'',qualification:'',phone:'',email:'',joiningDate:today(),contractType:'permanent',baseSalary:0,status:'active'});
  const [attendance,setAttendance]=useState({staffId:'',attendanceDate:today(),status:'present',note:''});
  const [leave,setLeave]=useState({staffId:'',leaveType:'casual',startDate:today(),endDate:today(),reason:''});
  const [payroll,setPayroll]=useState({staffId:'',period:month(),baseSalary:0,allowances:0,deductions:0,status:'draft',paidAt:'',notes:''});
  const [doc,setDoc]=useState({staffId:'',documentType:'joining',title:'',fileUrl:'',notes:''});
  const [note,setNote]=useState({staffId:'',note:'',rating:''});
  async function load(){setLoading(true); setData(await getHrOverview()); setLoading(false)}
  useEffect(()=>{load().catch(()=>setLoading(false))},[]);
  const staff=data?.staff||[]; const selectedStaff=staff.find(s=>s.id===payroll.staffId);
  async function submitStaff(e){e.preventDefault(); await saveStaff(staffForm); setStaffForm({...staffForm,name:'',employeeId:'',designation:'',department:'',qualification:'',phone:'',email:'',baseSalary:0}); load();}
  async function submitAttendance(e){e.preventDefault(); await markStaffAttendance(attendance); load();}
  async function submitLeave(e){e.preventDefault(); await requestStaffLeave(leave); load();}
  async function submitPayroll(e){e.preventDefault(); await savePayroll(payroll); load();}
  async function submitDoc(e){e.preventDefault(); await addStaffDocument(doc); setDoc({...doc,title:'',fileUrl:'',notes:''}); load();}
  async function submitNote(e){e.preventDefault(); await addPerformanceNote(note); setNote({...note,note:'',rating:''}); load();}
  useEffect(()=>{ if(selectedStaff && !payroll.baseSalary) setPayroll(p=>({...p,baseSalary:selectedStaff.baseSalary})); },[payroll.staffId]);
  if(loading)return <div className="flex h-48 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-[var(--brand)]" /></div>;
  return <div className="space-y-5"><div><h2 className="text-lg font-black text-slate-800">HR & Staff Management</h2><p className="text-sm text-slate-500">Non-teaching staff, attendance, leave, payroll, contracts, and performance records.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={BriefcaseBusiness} label="Active Staff" value={staff.filter(s=>s.status==='active').length} color="bg-emerald-50 text-emerald-600"/><Stat icon={CalendarCheck} label="Attendance Records" value={data?.attendance?.length||0} color="bg-blue-50 text-blue-600"/><Stat icon={WalletCards} label="Payroll Records" value={data?.payroll?.length||0} color="bg-amber-50 text-amber-600"/><Stat icon={Star} label="Performance Notes" value={data?.notes?.length||0} color="bg-purple-50 text-purple-600"/></div>
    <div className="flex flex-wrap gap-1 rounded-2xl border border-slate-200 bg-slate-50 p-1">{TABS.map(t=><button key={t} onClick={()=>setActive(t)} className={`rounded-xl px-3 py-2 text-sm font-bold ${active===t?'bg-white text-[var(--brand)] shadow-soft':'text-slate-500'}`}>{t}</button>)}</div>
    {active==='Staff'&&<><form onSubmit={submitStaff} className="card grid gap-4 lg:grid-cols-5"><Field label="Name"><Input required value={staffForm.name} onChange={e=>setStaffForm({...staffForm,name:e.target.value})}/></Field><Field label="Type"><Select value={staffForm.staffType} onChange={e=>setStaffForm({...staffForm,staffType:e.target.value})}><option value="non_teaching">Non-teaching</option><option value="support">Support</option><option value="admin">Admin</option></Select></Field><Field label="Designation"><Input value={staffForm.designation} onChange={e=>setStaffForm({...staffForm,designation:e.target.value})}/></Field><Field label="Department"><Input value={staffForm.department} onChange={e=>setStaffForm({...staffForm,department:e.target.value})}/></Field><Field label="Base Salary"><Input type="number" value={staffForm.baseSalary} onChange={e=>setStaffForm({...staffForm,baseSalary:e.target.value})}/></Field><Field label="Employee ID"><Input value={staffForm.employeeId} onChange={e=>setStaffForm({...staffForm,employeeId:e.target.value})}/></Field><Field label="Qualification"><Input value={staffForm.qualification} onChange={e=>setStaffForm({...staffForm,qualification:e.target.value})}/></Field><Field label="Phone"><Input value={staffForm.phone} onChange={e=>setStaffForm({...staffForm,phone:e.target.value})}/></Field><Field label="Email"><Input value={staffForm.email} onChange={e=>setStaffForm({...staffForm,email:e.target.value})}/></Field><div className="flex items-end"><button className="btn-primary"><Save className="h-4 w-4"/>Save</button></div></form>{staff.length?<Table rows={staff} cols={['name','designation','department','staffType','baseSalary','status']} action={s=><button onClick={()=>deleteStaff(s.id).then(load)} className="btn-danger"><Trash2 className="h-4 w-4"/></button>}/>:<Empty>No staff records yet.</Empty>}</>}
    {active==='Attendance'&&<><MiniForm onSubmit={submitAttendance} staff={staff} state={attendance} setState={setAttendance} fields={[['attendanceDate','date'],['status','select', ['present','absent','late']],['note','text']]}/><Table rows={data?.attendance} cols={['attendanceDate','staffName','status','note']}/></>}
    {active==='Leave'&&<><MiniForm onSubmit={submitLeave} staff={staff} state={leave} setState={setLeave} fields={[['leaveType','select',['casual','sick','earned','unpaid']],['startDate','date'],['endDate','date'],['reason','text']]}/><Table rows={data?.leaves} cols={['staffName','leaveType','startDate','endDate','status','reason']} action={l=><div className="flex gap-1"><button onClick={()=>reviewStaffLeave(l.id,'approved').then(load)} className="btn-secondary">Approve</button><button onClick={()=>reviewStaffLeave(l.id,'rejected').then(load)} className="btn-danger">Reject</button></div>}/></>}
    {active==='Payroll'&&<><MiniForm onSubmit={submitPayroll} staff={staff} state={payroll} setState={setPayroll} fields={[['period','text'],['baseSalary','number'],['allowances','number'],['deductions','number'],['status','select',['draft','approved','paid']],['paidAt','date'],['notes','text']]}/><Table rows={data?.payroll} cols={['period','staffName','baseSalary','allowances','deductions','netSalary','status']} moneyCols={['baseSalary','allowances','deductions','netSalary']}/></>}
    {active==='Documents'&&<><MiniForm onSubmit={submitDoc} staff={staff} state={doc} setState={setDoc} fields={[['documentType','select',['contract','joining','nid','certificate','other']],['title','text'],['fileUrl','text'],['notes','text']]}/><Table rows={data?.documents} cols={['staffName','documentType','title','fileUrl','notes']}/></>}
    {active==='Performance'&&<><MiniForm onSubmit={submitNote} staff={staff} state={note} setState={setNote} fields={[['rating','number'],['note','text']]}/><Table rows={data?.notes} cols={['staffName','rating','note','createdAt']}/></>}
  </div>;
}
function MiniForm({onSubmit,staff,state,setState,fields}){return <form onSubmit={onSubmit} className="card grid gap-4 lg:grid-cols-5"><Field label="Staff"><Select required value={state.staffId} onChange={e=>setState({...state,staffId:e.target.value})}><option value="">Select staff</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</Select></Field>{fields.map(([k,type,opts])=><Field key={k} label={k.replace(/[A-Z]/g,m=>' '+m)}>{type==='select'?<Select value={state[k]} onChange={e=>setState({...state,[k]:e.target.value})}>{opts.map(o=><option key={o} value={o}>{o}</option>)}</Select>:<Input required={['title','note','startDate','endDate'].includes(k)} type={type} value={state[k]||''} onChange={e=>setState({...state,[k]:e.target.value})}/>}</Field>)}<div className="flex items-end"><button className="btn-primary"><Plus className="h-4 w-4"/>Add</button></div></form>}
function Table({rows=[],cols=[],action,moneyCols=[]}){if(!rows.length)return <Empty>No records.</Empty>;return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-sm"><thead><tr className="bg-slate-50 text-left text-xs font-bold uppercase text-slate-400">{cols.map(c=><th key={c} className="px-4 py-3">{c}</th>)}{action&&<th/>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i} className="border-b border-slate-50">{cols.map(c=><td key={c} className="px-4 py-3 text-slate-700">{moneyCols.includes(c)?money(r[c]):String(r[c]??'')}</td>)}{action&&<td className="px-4 py-3 text-right">{action(r)}</td>}</tr>)}</tbody></table></div>}